language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
script:
  - gem install test-unit
  - ruby selenium/tests/first_suite.rb > result.txt
  - gem install pony
env:
  global:
    - secure: "SQ3jhq1SWUZuCmPhEY3gLTB806YyHQq2euDhgcASozgeZNVzR7tPiLl6gJA9\nKus47YpvhpaSWhk0Fp+f9DqeYCTMs865YvXSyP0gsw47ph5lhI5oyV/R5lbi\n/Dh/1BKmADuIq6IyWdWicDw0JiS39GC6Uuumybl5ktiLyVRrdy4="
    - secure: "MqMB2UXc6zpMnr11c8mjuw/IwLOcRpmIq8L/31W4xd+grhIrj6B2zZSep7rt\ng7vbcyzMVajUdw7/An1jeB8juhaGUGL3YnxVAkQWTpfdDkCuOoM4vjh9vgUY\n0mgFq40oTB7ye3sP2acfeDkvs5dXznxQiIt9byWUmq7cSwK3AIo="
before_script:
  - rake db:migrate
  - sudo apt-get install sendmail sendmail-base sendmail-bin sendmail-cf mailutils
  - "sudo /etc/init.d/sendmail reload"
after_script:
  - ruby selenium/mail.rb 
after_success:
  
after_failure:
  
notifications:
  recipients:
      - rohini@neevtech.com
  email: false
    



