language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
script:
  - "se-interpreter interpreter_config.json"
env:
  global:
    - secure: "SLoCuXPwhSO2waXOPKOUCHG9gEaXqqvUWV47JVUYb/KsicGEHiDvIq0esgta\nbAnQNn5iIjMo9OlvgDhvr9ravkTXZpF1Df8A7RBT/uSgksiXDNUgbEQ41bwf\nqFCVK4xdXNHXxiYAuKO1Dlb8uSiGBByaLEHKHOyaxTc0UojCFcI="
    - secure: "Cr3HAYlfPxue4ROsbjOJaWWeyv/UlTUFhPUFB+IoiWXMtBZA85W8+eeykwH1\nCrPtLiq/57y+p3oZvsbWDEGQsK+YNT3YMYxjh6woXRUwA7mJc/s45apMwNV4\nwx6N2BEaHmDCOwcfwceYDr1vWF6h/MK2uA+XJH2JarDZWEugj00="
before_script:
  - "npm install -g se-interpreter"
  - rake db:migrate
